version: '3.8'

services:
  u2net:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: u2net-container
    stdin_open: true
    tty: true
    volumes:
      - ./:/app  # Mount the local directory into the container
    ports:
      - "7860:7860"  # Port mapping for Gradio web interface
